### ISSUE TITLE
MySql Connection setting problem

### ISSUE THREAD

**Issue by ahesanath** [jkvor/emysql#4]
Hi,
Following error coming when try to add pool. (This was initiated by parallel processes)
{'EXIT',{failed_to_connect_to_database,emfile}
Fllowing is the Erlang Code
case catch emysql:add_pool(ConnPoolId, 10, UName, Pw, host,Port, "test", utf8) of
        ok ->  
{ok, ConnPoolId};
        {error, pool_already_exists} ->
            already_exist;
        {'EXIT',{failed_to_connect_to_database, emfile}} ->
            io:fwrite("Else set_connection ~p~n",[{{failed_to_connect_to_database, emfile}, DbName, ConnPoolId}]),
            catch spawn(?MODULE, update_status,["failed_to_connect_to_database"]),
            error;
        Else ->
            catch spawn(?MODULE, update_status,["database_error"]),
            io:fwrite("Else set_connection ~p~n",[{Else, DbName, ConnPoolId}]),
            error
    end. 

Pls help to solve this issue.
Br,
Sanath

**Comment by wmw** [comment]
Hey there ahesanath. This project is no longer maintained. You should try the fork located here: https://github.com/Eonblast/Emysql -- it is still under active development and may resolve your issue.

**Comment by ahesanath** [comment]
Hi,
Tx a lot for info
Br,
Sanath
